.TH ZSUIF_GATEWAY 1 "Apr 3 1998" "Princeton University" "Zephyr Project"
.SH NAME
zsuif_gateway \- translate a SUIF 2.0 file into ZSUIF
.SH SYNOPSIS
.B do_create_suif_hello_world
.I infile
.I outfile
.SH DESCRIPTION
The
.I zsuif_gateway
pass translates SUIF 2.0 into ZSUIF. It is a back end pass.
.SH OPTIONS
There are currently no options.
.SH HISTORY
This program was written by Daniel Wang.
