#!/bin/sh
# the path of the directory in which executables (like this file) are kept.

if [ -z "$ASDL_HOME" ] ; then
 PRG=`ksh whence $0`
 if [ "$?" != "0" ]; then
    echo "Unable to determine ASDL_HOME automatically please set it"
 fi
 PRG_DIR=`dirname $0`
 ASDL_HOME=`cd $PRG_DIR ; cd ..;/bin/pwd`
 export ASDL_HOME
fi

RUN_DIR=${ASDL_HOME}/lib/asdlGen/

# the path of the directory in which the heap images are kept.
HEAP_DIR=${ASDL_HOME}/lib/asdlGen/

#
# the following could be replaced with some site specific code
#
ARCH_N_OPSYS=`${ASDL_HOME}/share/asdlGen/sysname`
if [ "$?" != "0" ]; then
  echo "$CMD: unable to determine architecture/operating system"
  exit 1
fi
eval $ARCH_N_OPSYS
PRG_NAME=`basename $0`
RUN="$RUN_DIR/run.$ARCH-$OPSYS"
HEAP="@SMLload=$HEAP_DIR/$PRG_NAME.$ARCH-$OPSYS"

if [ ! -x "$RUN" ]; then
  echo "$CMD: cannot find runtime system $RUN"
  exit 1
fi

#
# run the sucker!
#
exec $RUN @SMLcmdname=$0 $HEAP $@




